SELECT 'Oracle mania', UPPER('Oracle mania') AS "대문자",
LOWER('Oracle mania') AS "소문자",
INITCAP('Oracle mania') AS "첫 글자 대문자" FROM DUAL;

SELECT LOWER(ENAME), INITCAP(JOB) FROM employee;

SELECT ENO, ENAME, DNO FROM employee
WHERE ENAME = UPPER('SCOTT');

SELECT LENGTH('ORACLE MANAGER'),
LENGTH('오라클 매니저') FROM DUAL;

SELECT CONCAT('ORACLE', 'MANIA') FROM DUAL;
SELECT 'ORACLE' || 'MANIA' FROM DUAL;

SELECT CONCAT(ENAME, SALARY) FROM employee;
SELECT SUBSTR('ORACLE MANIA', 4, 3), 
SUBSTR('ORACLE MANIA', -1, 1) FROM DUAL;
 
SELECT INSTR('ORACLE MANIA', 'A') FROM DUAL;
SELECT LPAD(SALARY, 10, '*')
FROM EMPLOYEE;

SELECT 'Oracle mania'
    , LTRIM('  Oracle mania  ')
    , RTRIM('  Oracle mania  ')
    , TRIM('  Oracle mania  ')
FROM DUAL;

SELECT HIREDATE, SUBSTR(HIREDATE, 1, 2), SUBSTR(HIREDATE, 4, 2) FROM employee;
SELECT 98.7654
    , ROUND(98.7654)
    , ROUND(98.7654, 2)
    , ROUND(98.7654, 1)
    , ROUND(98.7654, -1)
FROM DUAL;
SELECT 98.7654
    , TRUNC(98.7654) 
    , TRUNC(98.7654, 2) 
    , TRUNC(98.7654, -1)
FROM DUAL; 

SELECT 98.7654
    , FLOOR(98.7654)
FROM DUAL;
SELECT 98.7654
    ,CEIL(98.7654)
FROM DUAL;
SELECT MOD(31,2)
FROM DUAL;

SELECT ENAME, MOD(SALARY, 500) FROM employee;
SELECT SYSDATE FROM DUAL;

SELECT INITCAP(ENAME), TRUNC(SYSDATE-HIREDATE) FROM employee;
SELECT SYSDATE   AS 오늘
    ,SYSDATE - 1 AS 어제
    ,SYSDATE + 1 AS 내일
FROM DUAL;