SELECT ENAME, HIREDATE, TO_CHAR(HIREDATE, 'YY-MM') AS 단축날짜,
TO_CHAR(HIREDATE, 'YYYY-MM-DD HH24:MI:SS') AS 날짜
FROM EMPLOYEE;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') FROM DUAL;

SELECT ENAME, SALARY, TO_CHAR(SALARY, 'L999,999'),
TO_CHAR(SALARY, 'L000,000')
FROM EMPLOYEE;

SELECT ENAME, HIREDATE FROM EMPLOYEE
WHERE HIREDATE = TO_DATE('19810220', 'YYYYMMDD');

SELECT ENAME, HIREDATE FROM EMPLOYEE
WHERE HIREDATE = TO_DATE('19810220');

SELECT 
TO_NUMBER('100,000', '999,999'),
 TO_NUMBER('900,000', '999,999') 
FROM DUAL;

SELECT NVL(COMMISSION, '상여금없음')
FROM EMPLOYEE;

SELECT ENAME, DECODE(DNO,
        10, '회계부'
        , 20, '연구소'
        , 30, '판매부'
        , 40, '운영부'
        , '디폴트') AS 부서명
FROM EMPLOYEE;

SELECT ENAME, DNO
    ,CASE WHEN DNO=10 THEN '회계부'
        WHEN DNO=20 THEN '연구소'
        WHEN DNO=30 THEN '판매부'
        WHEN DNO=40 THEN '운영부'
        ELSE '디폴트'
    END                             AS 부서명
FROM EMPLOYEE;