SELECT JOB, SUM(SALARY) AS 총합
, MAX(SALARY) AS 최고액
, MIN(SALARY) AS 최소액
, ROUND(AVG(SALARY)) AS 평균
FROM EMPLOYEE
GROUP BY JOB;

SELECT SUM(SALARY) AS 총합
, MAX(SALARY) AS 최고액
, MIN(SALARY) AS 최소액
, ROUND(AVG(SALARY)) AS 평균
FROM EMPLOYEE;

SELECT JOB, COUNT(*) FROM EMPLOYEE
GROUP BY JOB;

SELECT COUNT(MANAGER) FROM EMPLOYEE;

SELECT MAX(SALARY) - MIN(SALARY) AS 차액 FROM EMPLOYEE;


--  연습문제 6) 직급별(JOB) 사원의 최저 급여를(SALARY) 출력하세요, 
--  단, 관리자를(MANAGER) 알 수 없는 사원 및 최저 급여가 2000 미만인 그룹은 제외시키고,
--  급여에 대한 내림차순으로 정렬해서 출력하세요
--  힌트) 0) ~ 컬럼별 : GROUP BY 컬럼 사용 
--       1) 관리자가 있는 사원 : WHERE MANAGER IS NOT NULL
--       2) 최저 급여가(MIN(SALARY)) >= 2000 이상인 그룹 : 
--          HAVING MIN(SALARY)>= 2000
--       3) ORDER BY MIN(SALARY) DESC;
SELECT JOB, MIN(SALARY) FROM EMPLOYEE
WHERE MANAGER IS NOT NULL
GROUP BY JOB
HAVING MIN(SALARY) >= 2000
ORDER BY MIN(salary)DESC;

SELECT DNO, COUNT(*), ROUND(AVG(SALARY),2) AS 평균급여 FROM EMPLOYEE
GROUP BY DNO;

SELECT DNO, FLOOR(AVG(SALARY)), MAX(SALARY), MIN(SALARY) FROM EMPLOYEE
GROUP BY DNO;

SELECT JOB, COUNT(*) FROM EMPLOYEE
GROUP BY JOB
HAVING COUNT(*) >=3;

SELECT TO_CHAR(HIREDATE, 'YYYY'), DNO, COUNT(*) FROM EMPLOYEE
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DNO;