-- 10_Join.sql
-- 조인(*****) : 
-- why? 2개 이상의 sql 문을 1개의 문장으로 속도를 증진시키는 방법
--   2개 이상 sql 문 단점 : 1) 2번 실행되므로 속도저하
--                         2) 네트웍 통해 db 서버로 전송됨
-- 예제1) 사원번호가(ENO) 7788 인 사원의 부서명은(DNAME) 뭘까요?
-- 사원 : EMPLOYEE
-- 부서 : DEPARTMENT
SELECT * 
FROM EMPLOYEE
WHERE ENO = 7788;
-- 결과 : 부서명 없음, 부서번호 있음(DNO) => 부서테이블을 또 조회 필요
-- 부서번호 : 20

SELECT *
FROM DEPARTMENT
WHERE DNO = 20;

SELECT EMPLOYEE.*, DEPARTMENT.* FROM EMPLOYEE, DEPARTMENT -- SELECT *을 하면 모든 컬럼을 가져오지만 서로 다른 테이블에 같은 이름의 컬럼이 있을 수 있으므로 각각 *을 해주어야한다.
WHERE EMPLOYEE.DNO = DEPARTMENT.DNO -- 공통 컬럼이 있어야함. 대부분의 JOIN을 이렇게 함
AND EMPLOYEE.ENO = 7788; -- 공통 컬럼이 있어야함. 대부분의 JOIN을 이렇게 함

SELECT EM.*, DE.* FROM EMPLOYEE EM, DEPARTMENT DE
WHERE EM.DNO = DE.DNO 
AND EM.ENO = 7788;

SELECT EM.*, DE.* FROM EMPLOYEE EM, DEPARTMENT DE
WHERE EM.DNO = DE.DNO AND EM.ENO IN( 7499,  7900);

SELECT EM.*, DE.* FROM EMPLOYEE EM, DEPARTMENT DE
WHERE EM.DNO = DE.DNO
AND EM.ENO BETWEEN 7500 AND 7700
AND DE.DNAME = 'SALES';

SELECT EM.*, DE.* 
FROM EMPLOYEE EM, DEPARTMENT DE

SELECT ENAME, SALARY, GRADE
FROM EMPLOYEE EM
    ,SALGRADE SA
WHERE EM.SALARY BETWEEN SA.LOSAL AND SA.HISAL;

SELECT EM.ENAME, MA.ENAME FROM EMPLOYEE EM, EMPLOYEE MA
WHERE EM.MANAGER = MA.MANAGER;

SELECT EM.ENAME, EM.DNO, DE.DNAME FROM EMPLOYEE EM, DEPARTMENT DE
WHERE EM.DNO = DE.DNO
AND EM.ENAME = 'SCOTT';

SELECT EM.ENAME, DE.LOC, DE.DNAME FROM EMPLOYEE EM, DEPARTMENT DE
WHERE EM.DNO = DE.DNO;

SELECT EM.ENAME, DE.DNAME ,DE.LOC FROM EMPLOYEE EM, DEPARTMENT DE
WHERE COMMISSION IS NOT NULL
AND EM.DNO = DE.DNO;

SELECT EM.ENAME, DE.DNAME FROM EMPLOYEE EM, DEPARTMENT DE
WHERE EM.ENAME LIKE '%A%'
AND EM.DNO = DE.DNO;

SELECT EM.ENAME, EM.JOB, DE.DNAME FROM EMPLOYEE EM, DEPARTMENT DE
WHERE EM.DNO = DE.DNO
AND DE.LOC = 'NEW YORK';

SELECT EM.DNO AS 부서번호
, DE.DNAME AS 부서명
,DE.LOC AS 위치
, ROUND(AVG(SALARY),1) AS 평균월급
, COUNT(*) AS 사원수
FROM EMPLOYEE EM, DEPARTMENT DE
WHERE EM.DNO = DE.DNO
GROUP BY EM.DNO, DE.DNAME, DE.LOC;

SELECT DE.DNAME AS 부서명
, EM.SALARY AS 급여
, COUNT(*) AS 사원수
FROM EMPLOYEE EM, DEPARTMENT DE
WHERE EM.DNO = DE.DNO;

SELECT DE.DNAME AS 부서명
, EM.JOB AS 업무
FROM EMPLOYEE EM, DEPARTMENT DE
WHERE EM.DNO = DE.DNO
GROUP BY DE.DNAME, EM.JOB
HAVING SUM(SALARY) >= 5000;

SELECT DE.DNAME AS 부서명
, EM.DNO AS 부서번호
, EM.ENO AS 사원번호
, EM.ENAME AS 사원명
FROM EMPLOYEE EM, DEPARTMENT DE
WHERE EM.DNO = DE.DNO
AND SALARY >= 2000;

SELECT ROUND(AVG(SALARY)), MAX(SALARY), MIN(SALARY), COUNT(*)
FROM EMPLOYEE
GROUP BY DNO;