SELECT SALARY FROM EMPLOYEE
WHERE ENAME ='SCOTT';

SELECT ENAME FROM EMPLOYEE
WHERE SALARY > 3000;

SELECT ENAME 
FROM EMPLOYEE
WHERE SALARY > (SELECT SALARY 
                FROM EMPLOYEE
                WHERE ENAME ='SCOTT');

SELECT ENAME 
FROM EMPLOYEE
WHERE DNO = (SELECT DNO 
                FROM EMPLOYEE
                WHERE ENAME ='SCOTT');