-- UPDATE
UPDATE DEPT_COPY
SET
    DNAME = 'PROGRAMMING'
WHERE DNO = 10;

UPDATE DEPT_COPY
SET
    DNAME = 'HR'
WHERE DNO = 20;

COMMIT;

SELECT *  FROM DEPT_COPY;

UPDATE DEPT_COPY
SET
    DNAME = 'PROGRAMMING2',
    LOC = 'SEOUL'
WHERE DNO = 10;

ROLLBACK;

-- 예제 4) 10 번 부서의 지역명을 (20번 부서의 지역명으로) 수정하기
SELECT LOC FROM DEPT_COPY
WHERE DNO = 20;

UPDATE DEPT_COPY
SET 
    LOC = (SELECT LOC 
            FROM DEPT_COPY
            WHERE DNO = 20)
WHERE DNO = 10;

SELECT DNO, LOC FROM DEPT_COPY;

COMMIT;

UPDATE DEPT_COPY
SET 
    LOC = (SELECT LOC
            FROM DEPT_COPY
            WHERE DNO = 30),
    DNAME = (SELECT DNAME
            FROM DEPT_COPY
            WHERE DNO = 30)
WHERE DNO = 10;

UPDATE DEPT_COPY
SET 
    (DNAME, LOC) = (SELECT DNAME, LOC
            FROM DEPT_COPY
            WHERE DNO = 30)
WHERE DNO = 10;

COMMIT;

-- DELETE삭제
DELETE FROM DEPT_COPY
WHERE DNO = 10;

SELECT * FROM DEPT_COPY;

DELETE FROM DEPT_COPY
WHERE DNO = 20;

DELETE FROM DEPT_COPY
WHERE DNO = (SELECT DNO FROM DEPT_COPY WHERE DNAME = 'SALES');

COMMIT;